version: '{build}'

branches:
  only: 
  - master

cache:
  - x86_64-6.3.0-release-posix-seh-rt_v5-rev1.7z
  - x86_64-4.8.4-release-posix-seh-rt_v3-rev0.7z

environment:
  MINGW_DIR: mingw64
  
  matrix:
    - BUILD_TYPE: Release
      ASSERTIONS: OFF
      TOOLS: ON
      MINGW_URL: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/6.3.0/threads-posix/seh/x86_64-6.3.0-release-posix-seh-rt_v5-rev1.7z/download
      MINGW_ARCHIVE: x86_64-6.3.0-release-posix-seh-rt_v5-rev1.7z
    - BUILD_TYPE: Debug
      ASSERTIONS: ON
      TOOLS: OFF
      MINGW_URL: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/6.3.0/threads-posix/seh/x86_64-6.3.0-release-posix-seh-rt_v5-rev1.7z/download
      MINGW_ARCHIVE: x86_64-6.3.0-release-posix-seh-rt_v5-rev1.7z
    - BUILD_TYPE: Release
      ASSERTIONS: OFF
      TOOLS: ON
      MINGW_URL: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/4.8.4/threads-posix/seh/x86_64-4.8.4-release-posix-seh-rt_v3-rev0.7z/download
      MINGW_ARCHIVE: x86_64-4.8.4-release-posix-seh-rt_v3-rev0.7z
    - BUILD_TYPE: Debug
      ASSERTIONS: ON
      TOOLS: OFF
      MINGW_URL: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/4.8.4/threads-posix/seh/x86_64-4.8.4-release-posix-seh-rt_v3-rev0.7z/download
      MINGW_ARCHIVE: x86_64-4.8.4-release-posix-seh-rt_v3-rev0.7z

install:
  - git submodule update --init --recursive
  - if not exist "%MINGW_ARCHIVE%" appveyor DownloadFile "%MINGW_URL%" -FileName "%MINGW_ARCHIVE%"
  - 7z x -y "%MINGW_ARCHIVE%" > nul
  - python -m ensurepip
  - python -m pip install cpp-coveralls==0.3.11
  # CMake refuses to generate MinGW Makefiles if sh.exe is in the Path
  - ps: Get-Command sh.exe -All | Remove-Item

before_build:
  - set Path=%CD%\%MINGW_DIR%\bin;%Path%
  - g++ --version
  - mingw32-make --version
  - cmake --version
  - mkdir build
  - cd build
  - cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DANKI_EXTRA_CHECKS=%ASSERTIONS% -DANKI_BUILD_TESTS=ON -DANKI_BUILD_SAMPLES=ON -DANKI_BUILD_TOOLS=%TOOLS%

build_script:
  - mingw32-make -j 2

notifications:
  email: false

