# Linux build configuration for Travis

language: cpp
sudo: false
dist: trusty
os: linux

compiler:
  - gcc
  - clang

env:
  - BUILD_TYPE=Debug EXTRA_CHECKS=ON TRACE=ON
  - BUILD_TYPE=Release EXTRA_CHECKS=OFF TRACE=OFF

cache:
  apt: true

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - cmake
      - g++-4.9

before_install:
  # Set the newer gcc on Linux
  - export CXX="g++-4.9"
  - export CC="gcc-4.9"

script:
  - mkdir build 
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DANKI_EXTRA_CHECKS=${EXTRA_CHECKS} -DANKI_BUILD_TOOLS=ON -DANKI_BUILD_TESTS=ON -DANKI_ENABLE_TRACE=${TRACE}
  - make -j 2

branches:
  only:
    - master

notifications:
  email: false

